### ISSUE TITLE
Comparison results of other methods in BasicVSR

### ISSUE THREAD

**Issue by mrluin** [ckkelvinchan/BasicVSR-IconVSR#11]
Hello kelvin,

Thanks for your great work! I am very interest in your work, BasicVSR and BasicVSR++, and I have some questions.

In paper, you provided comprehensive comparison of existing VideoSR methods. I noticed that some methods, such as RBPN and EDVR did not have BD experiments in original paper, and methods such as DUF and PFNL did not have BI experiments in their paper. 

As for the results of these methods, did you retrain them from scratch? 

Best regards,
Jingbo

**Comment by ckkelvinchan** [comment]
Yes, we retrain the methods. We train the models with several sets of hyperparameters and report their best results. We cannot guarantee optimality though.
