### ISSUE TITLE
about the evaluation settings on vimeo-90k-T

### ISSUE THREAD

**Issue by zslzx** [ckkelvinchan/BasicVSR-IconVSR#12]
Hi,
Thanks for your excellent work. 
I'm curious about some details about your evaluation settings on vimeo-90k-T. Are the PSNR and SSIM calculated on all the frames, or just on the 4th frame? Did you use the flip strategy to produce 14-frame sequences during evaluation?
Thanks again.

**Comment by ckkelvinchan** [comment]
Hello @zslzx, thanks for your interest in our work. 

Following earlier conventions, we compute the PSNR and SSIM only for the 4th frame. And yes, we use 14 frames in the evaluation.

**Comment by zslzx** [comment]
Thank you for your explanation, very helpful.
