### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by linjing7** [ckkelvinchan/BasicVSR-IconVSR#2]
Hi, it's a really excellent work. When will you publish the code? Will it be published In 2020?  Thanks a lot!

**Comment by ckkelvinchan** [comment]
Thanks a lot for your interest. We are trying our best. We want to make sure the code is in good condition and easy to use. We will release the code once it is ready.

**Comment by linjing7** [comment]
okay, thanks a lot !

**Comment by ckkelvinchan** [comment]
Sorry for the late reply. We have been dealing with some internal issues. The codes will be released soon. Thanks again.
