### ISSUE TITLE
details about training

### ISSUE THREAD

**Issue by linjing7** [ckkelvinchan/BasicVSR-IconVSR#3]
Hi, thank you very much for your excellent work. I have some question about the training deails:
1. As we know, the input of the network is [B, T, C, H, W], does T remain the same during training and inference? If T=100 during training, it's really slow.
2. Detail about the cosine annealing scheme: could you please tell me about the T_period? Did you use the restarts method?

Thank you again for your nice work.

**Comment by Feynman1999** [comment]
waiting the answer too

**Comment by huxiaotaostasy** [comment]
If T=100 during training, it's not just slow, I think it will lead to OOM. The sequences are too large and the parameters are all be stored to calculate the grads.

**Comment by ckkelvinchan** [comment]
Thank you for your interest in our work. Sorry for the late reply as we have been dealing with some internal issues. 

1. We do not use the whole sequence for training. We use 15 frames in training.
2. `T_period` equals the number of iterations (300K). That means, we do not use restart.

Finally, we will release our codes soon. Thanks again for your interest.
