### ISSUE TITLE
Request for pretrained model

### ISSUE THREAD

**Issue by quqixun** [ckkelvinchan/BasicVSR-IconVSR#6]
Thanks for you work!
Could you please release the pretrained model to mmedit model zoo?

**Comment by ckkelvinchan** [comment]
I am re-training the networks under the MMEditing framework to ensure reproducibility. The models will be released to MMEditing model zoo once it is finished. Stay tuned :)

**Comment by affromero** [comment]
@ckkelvinchan could you please let us know once you release the model?

**Comment by ckkelvinchan** [comment]
The pre-trained BasicVSR can be found here: https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/basicvsr
