### ISSUE TITLE
Merging to BasicSR?

### ISSUE THREAD

**Issue by affromero** [ckkelvinchan/BasicVSR-IconVSR#7]
Hello, I am aware you merged your code to the OpenMMLab framework. Is there a plan to also merge it to [BasicSR](https://github.com/xinntao/BasicSR)?
Thanks.

**Comment by ckkelvinchan** [comment]
We do not have this plan at the moment. Maybe you can have a try of our models in MMEditing :)

**Comment by iBobbyTS** [comment]
Do you plan to put the code in the seperate repo, I mean here, the BasicVSR repo.

**Comment by ckkelvinchan** [comment]
No, the main codes will not be put in this repo.
