### ISSUE TITLE
about GLEAN

### ISSUE THREAD

**Issue by liuliuliu11** [ckkelvinchan/BasicVSR-IconVSR#8]
I am currently a second-year Ph.D. student in Harbin Institute of Technology. I am supervised by Prof. Zuo Wangmeng. I am greatly interested in the work of GLEAN, could you share the code? Looking forward to your reply as soon as possible!

**Comment by ckkelvinchan** [comment]
Hello, thank you for your interest in GLEAN!

I am now reproducing GLEAN in MMEditing framework. It should be ready in one or two weeks' time. Thanks for your interest again.
