### ISSUE TITLE
BasicVSR++

### ISSUE THREAD

**Issue by pepinu** [ckkelvinchan/BasicVSR-IconVSR#9]
Hello,

Thanks for making your code public, wonderful work. 

I've read that you & your team further improved the architecture as shown [here](https://arxiv.org/pdf/2104.13371.pdf). Are there any plans of releasing basicVSR++ models in the future?

Best Regards,
Jeremi Podlasek

**Comment by Thomasedv** [comment]
They have addressed this here:
https://github.com/open-mmlab/mmediting/issues/283

**Comment by pepinu** [comment]
thanks!
